CREATE TABLE IF NOT EXISTS purchase_order (
    id VARCHAR(32) NOT NULL COMMENT 'UUID',
    order_sn VARCHAR(50) DEFAULT '' COMMENT '采购单号',
    custom_order_sn VARCHAR(50) DEFAULT '' COMMENT '自定义单号',
    supplier_id INT DEFAULT 0 COMMENT '供应商id',
    auditor_realname VARCHAR(50) DEFAULT '' COMMENT '审核人姓名',
    opt_realname VARCHAR(50) DEFAULT '' COMMENT '操作人姓名',
    last_realname VARCHAR(50) DEFAULT '' COMMENT '最后操作人姓名',
    create_time DATETIME COMMENT '创建时间',
    order_time DATETIME COMMENT '下单时间',
    status INT DEFAULT 0 COMMENT '采购单状态',
    status_text VARCHAR(20) DEFAULT '' COMMENT '状态说明',
    item_wid INT DEFAULT 0 COMMENT '仓库id(子项)',
    item_sku VARCHAR(200) DEFAULT '' COMMENT 'SKU(子项)',
    item_product_name VARCHAR(200) DEFAULT '' COMMENT '品名(子项)',
    item_quantity_real INT DEFAULT 0 COMMENT '实际采购量(子项)',
    item_quantity_entry INT DEFAULT 0 COMMENT '到货入库量(子项)',
    upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_order_sn (order_sn),
    KEY idx_create_time (create_time),
    KEY idx_item_wid (item_wid),
    KEY idx_item_sku (item_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单(含子项)';
