CREATE TABLE IF NOT EXISTS warehouse_statement (
    id VARCHAR(32) NOT NULL COMMENT 'UUID',
    statement_id VARCHAR(50) DEFAULT '' COMMENT '流水ID',
    wid INT DEFAULT 0 COMMENT '仓库id',
    ware_house_name VARCHAR(100) DEFAULT '' COMMENT '仓库名称',
    order_sn VARCHAR(100) DEFAULT '' COMMENT '操作单据号',
    ref_order_sn VARCHAR(100) DEFAULT '' COMMENT '关联单据号',
    sku VARCHAR(200) DEFAULT '' COMMENT 'SKU',
    seller_id VARCHAR(50) DEFAULT '' COMMENT '店铺id',
    fnsku VARCHAR(100) DEFAULT '' COMMENT 'FNSKU',
    opt_time DATETIME COMMENT '操作时间',
    type INT DEFAULT 0 COMMENT '流水类型',
    type_text VARCHAR(50) DEFAULT '' COMMENT '流水类型文本',
    sub_type VARCHAR(20) DEFAULT '' COMMENT '子类型',
    sub_type_text VARCHAR(100) DEFAULT '' COMMENT '子类型文本',
    product_name VARCHAR(200) DEFAULT '' COMMENT '品名',
    product_good_num INT DEFAULT 0 COMMENT '可用量',
    product_bad_num INT DEFAULT 0 COMMENT '次品量',
    upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_stmt (statement_id),
    KEY idx_sku (sku),
    KEY idx_wid (wid),
    KEY idx_opt_time (opt_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='仓库库存流水';
