DROP TABLE IF EXISTS purchase_order;
CREATE TABLE purchase_order (
    id VARCHAR(32) NOT NULL COMMENT 'UUID',
    order_sn VARCHAR(50) DEFAULT '' COMMENT '采购单号',
    custom_order_sn VARCHAR(50) DEFAULT '' COMMENT '自定义单号',
    supplier_id INT DEFAULT 0 COMMENT '供应商id',
    supplier_name VARCHAR(200) DEFAULT '' COMMENT '供应商',
    opt_uid INT DEFAULT 0 COMMENT '采购员id',
    opt_realname VARCHAR(50) DEFAULT '' COMMENT '操作人姓名',
    auditor_realname VARCHAR(50) DEFAULT '' COMMENT '审核人姓名',
    last_realname VARCHAR(50) DEFAULT '' COMMENT '最后操作人姓名',
    create_time DATETIME COMMENT '创建时间',
    order_time DATETIME COMMENT '下单时间',
    update_time VARCHAR(50) DEFAULT '' COMMENT '采购单更新时间',
    status INT DEFAULT 0 COMMENT '采购单状态',
    status_text VARCHAR(20) DEFAULT '' COMMENT '状态说明',
    wid INT DEFAULT 0 COMMENT '仓库id',
    ware_house_name VARCHAR(100) DEFAULT '' COMMENT '仓库名',
    item_sku VARCHAR(200) DEFAULT '' COMMENT '子项SKU',
    item_product_name VARCHAR(200) DEFAULT '' COMMENT '子项品名',
    item_product_id INT DEFAULT 0 COMMENT '子项产品id',
    item_quantity_real INT DEFAULT 0 COMMENT '子项实际采购量',
    item_quantity_entry INT DEFAULT 0 COMMENT '子项到货入库量',
    item_price DECIMAL(16,4) DEFAULT 0 COMMENT '子项含税单价',
    item_amount DECIMAL(16,4) DEFAULT 0 COMMENT '子项价税合计',
    raw_json JSON COMMENT '完整原始数据',
    upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_create (order_sn, create_time),
    KEY idx_create_time (create_time),
    KEY idx_item_sku (item_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单(全字段)';
